//go:build generate

// Regenerate chinaip_cn.txt.gz and chinaip_meta.go from the APNIC delegation
// statistics:
//
//	go run -tags generate chinaip_gen.go
//
// APNIC publishes the authoritative record of which ranges are delegated to
// organisations in each economy, it is refreshed daily, and unlike the
// community IPv4 lists MEOW used before it also covers IPv6.
package main

import (
	"bufio"
	"bytes"
	"compress/gzip"
	"encoding/binary"
	"fmt"
	"go/format"
	"log"
	"net/http"
	"net/netip"
	"os"
	"sort"
	"strconv"
	"strings"
	"time"
)

const delegationURL = "https://ftp.apnic.net/stats/apnic/delegated-apnic-latest"

func main() {
	prefixes, err := fetch(delegationURL)
	if err != nil {
		log.Fatalf("fetch delegation data: %v", err)
	}

	var v4, v6 []netip.Prefix
	for _, p := range prefixes {
		if p.Addr().Is4() {
			v4 = append(v4, p)
		} else {
			v6 = append(v6, p)
		}
	}
	if len(v4) == 0 || len(v6) == 0 {
		log.Fatalf("refusing to generate a truncated table: %d IPv4 and %d IPv6 prefixes", len(v4), len(v6))
	}
	sortPrefixes(v4)
	sortPrefixes(v6)

	day := time.Now().UTC().Format("2006-01-02")

	// The address table itself: a plain CIDR-per-line list, gzip-compressed and
	// embedded by chinaip.go. Keeping it out of Go source keeps a regeneration
	// to a one-line diff.
	var raw bytes.Buffer
	fmt.Fprintf(&raw, "# Code generated from %s on %s; DO NOT EDIT.\n", delegationURL, day)
	for _, list := range [][]netip.Prefix{v4, v6} {
		for _, p := range list {
			raw.WriteString(p.String())
			raw.WriteByte('\n')
		}
	}
	var gzBuf bytes.Buffer
	gz, _ := gzip.NewWriterLevel(&gzBuf, gzip.BestCompression)
	if _, err := gz.Write(raw.Bytes()); err != nil {
		log.Fatalf("gzip china ip data: %v", err)
	}
	if err := gz.Close(); err != nil {
		log.Fatalf("gzip china ip data: %v", err)
	}
	if err := os.WriteFile("chinaip_cn.txt.gz", gzBuf.Bytes(), 0644); err != nil {
		log.Fatalf("write chinaip_cn.txt.gz: %v", err)
	}

	var meta bytes.Buffer
	fmt.Fprintf(&meta, "// Code generated by chinaip_gen.go; DO NOT EDIT.\n\n")
	fmt.Fprintf(&meta, "package main\n\n")
	fmt.Fprintf(&meta, "const cnIPDataSource = %q\n", delegationURL)
	fmt.Fprintf(&meta, "const cnIPDataGenerated = %q\n", day)
	src, err := format.Source(meta.Bytes())
	if err != nil {
		log.Fatalf("format generated source: %v", err)
	}
	if err := os.WriteFile("chinaip_meta.go", src, 0644); err != nil {
		log.Fatalf("write chinaip_meta.go: %v", err)
	}

	log.Printf("wrote chinaip_cn.txt.gz (%d bytes) and chinaip_meta.go: %d IPv4 prefixes, %d IPv6 prefixes",
		gzBuf.Len(), len(v4), len(v6))
}

func sortPrefixes(prefixes []netip.Prefix) {
	sort.Slice(prefixes, func(i, j int) bool {
		if c := prefixes[i].Addr().Compare(prefixes[j].Addr()); c != 0 {
			return c < 0
		}
		return prefixes[i].Bits() < prefixes[j].Bits()
	})
}

func fetch(url string) ([]netip.Prefix, error) {
	resp, err := http.Get(url)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("unexpected status %s", resp.Status)
	}

	var out []netip.Prefix
	scanner := bufio.NewScanner(resp.Body)
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		// registry|cc|type|start|value|date|status[|extensions...]
		f := strings.Split(line, "|")
		if len(f) < 7 || f[1] != "CN" {
			continue
		}
		if f[6] != "allocated" && f[6] != "assigned" {
			continue
		}
		switch f[2] {
		case "ipv4":
			ps, err := ipv4Prefixes(f[3], f[4])
			if err != nil {
				return nil, fmt.Errorf("%s: %w", line, err)
			}
			out = append(out, ps...)
		case "ipv6":
			bits, err := strconv.Atoi(f[4])
			if err != nil {
				return nil, fmt.Errorf("%s: %w", line, err)
			}
			addr, err := netip.ParseAddr(f[3])
			if err != nil {
				return nil, fmt.Errorf("%s: %w", line, err)
			}
			p, err := addr.Prefix(bits)
			if err != nil {
				return nil, fmt.Errorf("%s: %w", line, err)
			}
			out = append(out, p)
		}
	}
	return out, scanner.Err()
}

// ipv4Prefixes converts an APNIC "start address + host count" record into CIDR
// prefixes. The count is a power of two but the start is not guaranteed to be
// aligned to it, so a record can need more than one prefix to express.
func ipv4Prefixes(start, count string) ([]netip.Prefix, error) {
	addr, err := netip.ParseAddr(start)
	if err != nil {
		return nil, err
	}
	if !addr.Is4() {
		return nil, fmt.Errorf("not an IPv4 address: %s", start)
	}
	n, err := strconv.ParseUint(count, 10, 64)
	if err != nil {
		return nil, err
	}
	if n == 0 || n > 1<<32 {
		return nil, fmt.Errorf("implausible host count %s", count)
	}

	b := addr.As4()
	lo := uint64(binary.BigEndian.Uint32(b[:]))
	hi := lo + n - 1

	var out []netip.Prefix
	for lo <= hi {
		// Largest aligned block that starts at lo and does not overrun hi.
		size := uint64(1)
		for size < hi-lo+1 && lo%(size*2) == 0 && lo+size*2-1 <= hi {
			size *= 2
		}
		bits := 32
		for s := size; s > 1; s /= 2 {
			bits--
		}
		var ab [4]byte
		binary.BigEndian.PutUint32(ab[:], uint32(lo))
		out = append(out, netip.PrefixFrom(netip.AddrFrom4(ab), bits))
		lo += size
	}
	return out, nil
}
